<?php

define("LMSG_ERROR", 0);
define("LMSG_SUCCESS", 1);
define("LMSG_FILL_FORM", 2);
define("LMSG_PRIVACY_POLICY", 3);
define("LMSG_WRONG_EMAIL", 4);
define("LMSG_WRONG_PASSWORD", 5);
define("LMSG_ACCOUNT_NAME_WRONG_SIZE", 6);
define("LMSG_ACCOUNT_EMAIL_ALREADY_USED", 7);
define("LMSG_ACCOUNT_NAME_ALREADY_USED", 8);
define("LMSG_FAIL_SEND_EMAIL", 9);
define("LMSG_FAIL_LOGIN", 10);
define("LMSG_RECOVERY_UNKNOWN_EMAIL", 11);
define("LMSG_RECOVERY_UNKNOWN_CHARACTER", 12);
define("LMSG_RECOVERY_WRONG_KEY", 13);
define("LMSG_RECOVERY_WRONG_SECRET_KEY", 14);
define("LMSG_RECOVERY_FILL_CHARACTER_NAME", 15);
define("LMSG_RECOVERY_DISABLED", 17);
define("LMSG_OPERATION_ARE_BLOCKED", 18);
define("LMSG_OPERATION_HAS_BLOCKED", 19);
define("LMSG_CHANGEPASS_WRONG_NEWPASS_CONFIRM", 20);
define("LMSG_CHANGEPASS_SAME_PASSWORD", 21);
define("LMSG_CHANGEPASS_WRONG_NEWPASS_LENGHT", 22);
define("LMSG_CHANGEEMAIL_ALREADY_HAVE_REQUEST", 23);
define("LMSG_CHARACTER_WRONG", 24);
define("LMSG_ACCOUNT_REGISTERED", 25);
define("LMSG_RECOVERY_ACCOUNT_NAME_SEND", 26);
define("LMSG_RECOVERY_PASSWORD_SEND", 27);
define("LMSG_RECOVERY_NEWPASS_SEND", 28);
define("LMSG_RECOVERY_BOTH_SEND", 29);
define("LMSG_RECOVERY_EMAIL_CHANGED", 30);
define("LMSG_ACCOUNT_PASSWORD_CHANGED", 31);
define("LMSG_CHANGEEMAIL_SCHEDULED", 32);
define("LMSG_ACCOUNT_INFOS_SEND", 33);
define("LMSG_ACCOUNT_PASSWORD_IS", 34);
define("LMSG_CHANGEEMAIL_NOTHING", 35);
define("LMSG_CHANGEEMAIL_CANCELED", 36);
define("LMSG_CHANGEINFOS_WRONG_SIZE", 37);
define("LMSG_CHANGEINFOS_SUCCESS", 38);
define("LMSG_SECRETKEY_ALREADY_EXISTS", 39);
define("LMSG_SECRETKEY_SUCCESS", 40);
define("LMSG_SECRETKEY_WRONG_SIZE", 41);
define("LMSG_SECRETKEY_CUSTOM_SUCCESS", 42);
define("LMSG_ACCOUNT_SETNAME_SAME_ID", 43);
define("LMSG_ACCOUNT_SETNAME_SUCCESS", 44);
define("LMSG_WRONG_NAME", 45);
define("LMSG_CHARACTER_NAME_ALREADY_USED", 46);
define("LMSG_ACCOUNT_CANNOT_HAVE_MORE_CHARACTERS", 47);
define("LMSG_CHARACTER_CREATED", 48);
define("LMSG_CHARACTER_NOT_TO_DELETION", 49);
define("LMSG_CHARACTER_NOT_FROM_YOUR_ACCOUNT", 50);
define("LMSG_CHARACTER_NO_MORE_DELETED", 51);
define("LMSG_CONTR_TERMS", 52);
define("LMSG_CONTR_ACTIVATED", 53);
define("LMSG_CONTR_ORDER_NUMBER_DUPLICATED", 54);
define("LMSG_CONTR_ORDER_CREATED", 55);
define("LMSG_ACCOUNT_HAS_NO_ORDERS", 56);
define("LMSG_REPORT", 57);
define("LMSG_NEED_LOGIN", 58);
define("LMSG_NEED_PREMIUM", 59);
define("LMSG_PAGE_NOT_FOUND", 60);
define("LMSG_SQL_INJECTION", 61);
define("LMSG_GUILD_NOT_FOUND", 62);
define("LMSG_GUILD_CHARACTER_NOT_INVITED", 63);
define("LMSG_GUILD_JOIN", 64);
define("LMSG_GUILD_JOIN_REJECT", 65);
define("LMSG_GUILD_NAME_ALREADY_USED", 66);
define("LMSG_GUILD_ONLY_ONE_VICE_PER_ACCOUNT", 67);
define("LMSG_CHARACTER_ALREADY_MEMBER_GUILD", 68);
define("LMSG_GUILD_CREATED", 69);
define("LMSG_CHARACTER_ALREADY_TO_DELETE", 70);
define("LMSG_CHARACTER_DELETION_SCHEDULED", 71);
define("LMSG_CHARACTER_COMMENT_WRONG_SIZE", 72);
define("LMSG_CHARACTER_COMMENT_CHANGED", 73);
define("LMSG_CHARACTER_CHANGE_THING_CONFIRM", 74);
define("LMSG_CHARACTER_NEED_OFFLINE", 75);
define("LMSG_CHARACTER_CHANGENAME_COST", 76);
define("LMSG_CHARACTER_NAME_CHANGED", 77);
define("LMSG_CHARACTER_CHANGESEX_COST", 78);
define("LMSG_CHARACTER_SEX_CHANGED", 79);
define("LMSG_ITEMSHOP_OLD_PURCHASE", 80);
define("LMSG_ITEMSHOP_COST", 81);
define("LMSG_ITEMSHOP_PURCHASE_SUCCESS", 82);
define("LMSG_GUILD_NEED_NO_MEMBERS_DISBAND", 83);
define("LMSG_GUILD_DISBANDED", 84);
define("LMSG_GUILD_COMMENT_SIZE", 85);
define("LMSG_GUILD_LOGO_SIZE", 86);
define("LMSG_GUILD_FILE_WRONG", 87);
define("LMSG_GUILD_LOGO_DIMENSION_WRONG", 88);
define("LMSG_GUILD_LOGO_EXTENSION_WRONG", 89);
define("LMSG_GUILD_DESC_CHANGED", 90);
define("LMSG_GUILD_INVITE_LIMIT", 91);
define("LMSG_GUILD_INVITE_ALREADY_MEMBER", 92);
define("LMSG_GUILD_INVITE_ALREADY_INVITED", 93);
define("LMSG_GUILD_INVITE_CHARACTER_NOT_FOUNDS", 94);
define("LMSG_GUILD_INVITEDS", 95);
define("LMSG_GUILD_LEAVE", 96);
define("LMSG_GUILD_IS_NOT_MEMBER", 97);
define("LMSG_GUILD_RANK_ONLY_PREMIUM", 98);
define("LMSG_GUILD_PERMISSION", 99);
define("LMSG_GUILD_TITLE_SIZE", 100);
define("LMSG_GUILD_ACCOUNT_ALREADY_IS_HIGH_RANK", 101);
define("LMSG_GUILD_MEMBER_EDITED", 102);
define("LMSG_GUILD_PASSLEADERSHIP", 103);
define("LMSG_GUILD_RANK_WRONG_ORDER", 104);
define("LMSG_GUILD_RANK_WRONG_SIZE", 105);
define("LMSG_GUILD_RANK_MIMINUM_NEEDED", 106);
define("LMSG_GUILD_RANKS_EDITED", 107);
define("LMSG_GUILD_RANK_IN_USE", 108);
define("LMSG_GUILD_CANNOT_LEAVE", 109);
define("LMSG_GUILD_WAR_NO_HAVE_OPPONENTS", 110);
define("LMSG_GUILD_NEED_TO_BE_FORMED", 111);
define("LMSG_FILL_NUMERIC_FIELDS", 112);
define("LMSG_GUILD_WAR_WRONG_FRAG_LIMIT", 113);
define("LMSG_GUILD_WAR_WRONG_END_DATE", 114);
define("LMSG_GUILD_WAR_WRONG_FEE", 115);
define("LMSG_GUILD_WAR_WRONG_COMMENT_LENGTH", 116);
define("LMSG_GUILD_WAR_DECLARED", 117);
define("LMSG_GUILD_WAR_ACCEPTED", 118);
define("LMSG_GUILD_WAR_REJECTED", 119);
define("LMSG_GUILD_WAR_NEGOTIATE_SEND", 120);
define("LMSG_GUILD_IS_ON_WAR", 121);
define("LMSG_GUILD_WAR_ALREADY", 122);
define("LMSG_GUILD_INVITE_CANCEL", 123);
define("LMSG_FORUM_ACCOUNT_NOT_HAVE_USER", 124);
define("LMSG_FORUM_ACCOUNT_NOT_HAVE_CHARACTERS", 125);
define("LMSG_FORUM_ACCOUNT_REGISTERED", 126);
define("LMSG_FORUM_POLL_ALREADY_VOTED", 127);
define("LMSG_FORUM_POLL_ONLY_FOR_PREMIUM", 128);
define("LMSG_FORUM_POLL_NEED_MIN_LEVEL", 129);
define("LMSG_FORUM_POLL_TIME_EXPIRED", 130);
define("LMSG_FORUM_POLL_VOTE_DONE", 131);
define("LMSG_FORUM_POST_TOO_LONG", 132);
define("LMSG_FORUM_POST_SENT", 133);
define("LMSG_FORUM_USER_BANNISHED", 134);
define("LMSG_STAMINA_NOT_HAVE_PREMDAYS", 135);
define("LMSG_STAMINA_VALUE_WRONG", 136);
define("LMSG_STAMINA_SUCCESSFULY", 137);
define("LMSG_DARGHOSPOINTS_NEED_ACCEPT_TERMS", 138);
define("LMSG_MONSTER_NOT_FOUND", 139);
define("LMSG_OPERATION_NEED_PREMDAYS", 140);
define("LMSG_ACCOUNT_CHANGENAME_SUCCESS", 141);
define("LMSG_GUILD_BALANCE_TOO_LOW", 142);
define("LMSG_SECRETKEY_MUST_BY_UNLIKE_REMINDER", 143);
define("LMSG_CAN_NOT_VALIDATE_EMAIL", 144);
define("LMSG_VALIDATE_EMAIL_SUCCESSFULY", 145);
define("LMSG_OPERATION_REQUIRE_VALIDATED_EMAIL", 146);
define("LMSG_ACCOUNT_ALREADY_VALIDATED_EMAIL", 147);
define("LMSG_ACCOUNT_VALIDATING_EMAIL_SEND", 148);

class Lang extends Lang_Messages{
	
	static function Message()
	{
		$args_num = func_num_args(); //numero de argumentos recebidos
		$args = func_get_args(); //array contendo os argumentos recebidos
		
		//o primeiro argumento (zero na array) sempre é a mensagem
		$messageid = $args[0];
		
		$message = self::$messages[$messageid];
		
		// os argumentos seguintes serão substituidos na mensagem pelo 
		// seu valor correspondente, argumento 1 na array em diante por
		// @v1@ em diante... se não ouver mais de 1 argumento, nada é feito
		if($args_num > 1)
		{
			for($i = 1; $i < $args_num; $i++)
			{
				$message = str_replace("@v{$i}@", $args[$i], $message);
			}
		}	
		
		return $message;
	}
}

?>